### ISSUE TITLE
"Malaka" is a swear word in Greek

### ISSUE THREAD

**Issue by impressivewebs** [nauvalazhar/code-design#20]
Was kind of funny to me, being Greek, but just thought I'd let you know. ;)

https://translate.google.com/?sl=el&tl=en&text=malaka&op=translate

**Comment by perdiDev** [comment]
Yeah, I know that. It's good name for Indonesian people. And you need to know that every country has unique words. And Malaka isn't bad word.

**Comment by nauvalazhar** [comment]
Hi, thank you for letting me know about that. The fact that I am not using Greek words as a reference, Malaka is the name of our Indonesian Philosopher and national hero, Tan Malaka. But, thank you for the insight.

I am going to close this issue for now, if you have any further questions or discussions, feel free to reopen it! 😃
