### ISSUE TITLE
[Feature] Adding OG metadata for improve viewer 

### ISSUE THREAD

**Issue by ioofy** [nauvalazhar/code-design#34]
**Is your feature request related to a problem? Please describe.**

No, i think if we adding og metadata its nice to have when paste a link and the crawl will be show metadata
that mean for improve view when user see metadata in every crawl platform like facebook, twitter, discord

what about you @nauvalazhar

**Comment by nauvalazhar** [comment]
Yeah, that's cool. I am going to remains this issue open since I still working on something else. Feel free to submit a pull request tho!

**Comment by ioofy** [comment]
> Yeah, that's cool. I am going to remains this issue open since I still working on something else. Feel free to submit a pull request tho!

Yep sure,

**Comment by sglkc** [comment]
I'd really like to contribute a PR to this issue, could you assign it to me? @nauvalazhar

**Comment by nauvalazhar** [comment]
Done.
