### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by rafiqola** [nauvalazhar/code-design#41]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Agencys -  Landing Page UI Design

**Figma Community URL**
(https://www.figma.com/community/file/1208800587833558237)

**Your Figma Profile**
The URL of your Figma profile. https://www.figma.com/@rafiqadha

**Comment by nauvalazhar** [comment]
Thank you for your contribution @rafiqola! I will add it to the collection.
