### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by rafiqola** [nauvalazhar/code-design#43]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Eventnity - Landing Page Ticket UI Design

**Figma Community URL**
https://www.figma.com/community/file/1210265697580558125

**Your Figma Profile**

- https://www.figma.com/@rafiqadha
- https://www.figma.com/@opik

**Comment by nauvalazhar** [comment]
Thank you for your contribution @rafiqola! I will add it to the collection.

**Comment by rafiqola** [comment]
Thanks for including me, I'm glad to be part of this collection!
