### ISSUE TITLE
[Feature] Can be scrolled up using back-to-top button

### ISSUE THREAD

**Issue by akbarsaputrait** [nauvalazhar/code-design#44]
**Is your feature request related to a problem? Please describe.**
Sometimes feels frustrated when it's already at the bottom and want to back to top of the page.

**Describe the solution you'd like**
Back-to-top button may help this problem

**Describe alternatives you've considered**

**Additional context**

**Comment by akbarsaputrait** [comment]
Can i contribute to this issue?

**Comment by nauvalazhar** [comment]
Oh, sure!

**Comment by nauvalazhar** [comment]
Resolved #60.
