### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by glennvhalado** [nauvalazhar/code-design#51]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Agency Landing Page

**Figma Community URL**
[Your UI design URL to the Figma community.](https://www.figma.com/community/file/1210888180615972372)

**Your Figma Profile**
The URL of your Figma profile. For example, https://figma.com/@glennvhalado

**Comment by nauvalazhar** [comment]
Thank you for your contribution, @glennvhalado! I will be looking into this.

**Comment by nauvalazhar** [comment]
We must rename your UI design to "Bubble Bash" to avoid confusion since others already used "Agency."
