### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by CandyAP** [nauvalazhar/code-design#52]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Construction Landing Page | Jhontraktor Clone

**Figma Community URL**
https://www.figma.com/community/file/1209577571885853711

**Your Figma Profile**
https://figma.com/@brainstewstudio

**Comment by nauvalazhar** [comment]
Thank you for your contribution, @CandyAP! I will be looking into this.
