### ISSUE TITLE
[Feature] Feature by Categories

### ISSUE THREAD

**Issue by mahdanidn** [nauvalazhar/code-design#53]
**Is your feature request related to a problem? Please describe.**
When I want to search for some design, but I want to concern to find Category Page Only

**Describe the solution you'd like**
Make button row by Category at button after difficult option.

**Describe alternatives you've considered**
..

**Additional context**
I want to contribute the feature if you agree to my feature

**Comment by nauvalazhar** [comment]
Hi, it seems like a good idea you have! We will be happy if you contribute to this feature!

**Comment by nauvalazhar** [comment]
Resolved at #55. Thank you, @mahdanidn.
