### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by xevorte** [nauvalazhar/code-design#58]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Suxz

**Figma Community URL**
https://www.figma.com/community/file/1211276735395024758

**Your Figma Profile**
https://figma.com/@irhammshidiq

**Comment by nauvalazhar** [comment]
Thank you for your contribution, @xevorte! I will add the design to the collection.
