### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by dzakiimuzh** [nauvalazhar/code-design#62]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Omah - Real Estate Website Design**
Your UI design project name. Must be short.

**https://www.figma.com/community/file/1213834016475813705**
Your UI design URL to the Figma community.

**https://www.figma.com/@dzakiimuzh**
The URL of your Figma profile. For example, https://figma.com/@mhd

**Comment by nauvalazhar** [comment]
Hi, @dzakiimuzh, thank you for your contribution! I will add the design to the collection.
