### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by afiiin** [nauvalazhar/code-design#71]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Agenone - Creative Digital Agency Landing Page

**Figma Community URL**
https://www.figma.com/community/file/1220307995673140735

**Your Figma Profile**
https://figma.com/@maafin_ui

**Comment by nauvalazhar** [comment]
Hi, thank you for your contribution, @afiiin! I will add the design to the collection.

**Comment by afiiin** [comment]
> Hi, thank you for your contribution, @afiiin! I will add the design to the collection.

you're welcome mas @nauvalazhar
