### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by irvanmoses** [nauvalazhar/code-design#78]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Team Collaboration Landing Page

**Figma Community URL**
https://www.figma.com/community/file/1033884363291199985

**Your Figma Profile**
https://figma.com/@irvan

**Comment by nauvalazhar** [comment]
Hi, thank you for your contribution, @irvanmoses! I will add the design to the collection.
