### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by rafiqmyura** [nauvalazhar/code-design#81]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Al Nasr - Website Al Hajj and Umrah

**Figma Community URL**
[Your UI design URL to the Figma community.](https://www.figma.com/community/file/1261583437014427177/Al-Nasr---Website-Al-Hajj-and-Umrah)

**Your Figma Profile**
The URL of your Figma profile. For example, https://figma.com/@rafiqadha

**Comment by nauvalazhar** [comment]
Hi, @rafiqmyura. Thank you for your design contribution!
