### ISSUE TITLE
New UI Design Contribution

### ISSUE THREAD

**Issue by alfianchii** [nauvalazhar/code-design#83]
Make sure you have read our [contributing guidelines](https://github.com/nauvalazhar/code-design/blob/main/CONTRIBUTING_DESIGN.md) before submitting this issue.

**Name**
Lidia

**Figma Community URL**
https://www.figma.com/community/file/1334838385104638513

**Your Figma Profile**
https://figma.com/@alpi

**Comment by nauvalazhar** [comment]
Thank you for your contribution @alfianchii!

**Comment by alfianchii** [comment]
Thank you so much!!

**Comment by alfianchii** [comment]
I forgot to add the design's description. Thank you so much for add its description anyway D:

![image](https://github.com/nauvalazhar/code-design/assets/76430369/958d6227-c093-4610-88c4-1e06c855bd36)

I will add the description into my Figma's file!
