### ISSUE TITLE
Read license link on challenge page unreadable

### ISSUE THREAD

**Issue by altafsyah** [nauvalazhar/code-design#86]
**Is your feature request related to a problem? Please describe.**

Hi,

I think the link to the license agreement on the challenge page is not very clear. At first, it doesn't appear to be a clickable link until you actually try to click it.

![image](https://github.com/nauvalazhar/code-design/assets/57579846/4e7dbbb8-34e8-406c-abaf-209b18ac723b)

**Describe the solution you'd like**
Maybe adding an underline would help to clear it? Since on the other page, link have underline on it.
![image](https://github.com/nauvalazhar/code-design/assets/57579846/aea738ba-63aa-4b11-8670-33c654309def)

**Describe alternatives you've considered**
Or maybe add the underline on hover, but i think it would be great to have it by default for consistency.

**Comment by altafsyah** [comment]
If you don't mind, I'd like to take this issue and work on fixing it.

**Comment by nauvalazhar** [comment]
Glad to hear that if you want to work on it. Can't wait for your PR, @altafsyah!
